### ISSUE TITLE
Android Emulator for Windows cannot unzip

### ISSUE THREAD

**Issue by ChenSenrui** [declan94/ssproject_jumper#5]
The zip file of Android Emulator for Windows is broken. It cannot be unzipped.  Please check what's wrong with it.

**Comment by zhangzw16** [comment]
We have checked that the file downloaded from that link works fine. Maybe it's because your connection was down while downloading the file. You should try to delete the file download it again :) @ChenSenrui

**Comment by ChenSenrui** [comment]
I change a download directory and now it works fine. Thanks for your help :) @zhangzw16
