### ISSUE TITLE
关于test.py的建议

### ISSUE THREAD

**Issue by NagisaZj** [declan94/ssproject_jumper#6]
在src文件夹写完了jumper.py后移植到test文件夹下，发现需要做很多不必要的修改。
个人建议：test.py只需调用我们写好的jumper.py，包括读图、跳跃等操作都由jumper.py负责，这样和src文件夹下的开发环境类似，移植起来会方便很多。

**Comment by robertying** [comment]
Closed by b3674e8f06cc997dbae4526da13da872504ae32b
